#AWS
S3_ARRIVAL_BUCKET: testfbdmediasharedresources-filearrivalbucket-nasbfsnhm0my
S3_VAULT_BUCKET:  	testfbdmediasharedresources-mediavaultbucket-sxmvrrp8asdl
S3_DPP_BUCKET: testfbdmediasharedresources-dppbucket-189omd2yngr4n
S3_CHECKSUM_BUCKET: testfbdmediasharedresources-checksumbucket-gywb5a0knxle
S3_PROXY_BUCKET: testfbdmediasharedresources-proxybucket-qu5mhuwku9iw
S3_DELIVERY_BUCKET: testmodavsharedresources-filearrivalbucket-1izk4p9v7f8vi
#Folder Under vault
PROXY_ARRIVED: proxy
TEST_PROXY_FILE: proxy/bbc_proxy.mp4
DEMO_TEST_PROXY_FILE: true
VAULT_ARRIVED: arrived
VAULT_QUARANTINE: quarantined
#Folder Under vault
S3_OUTBOUND_BUCKET: testfbdmediasharedresources-outboundmediabucket-10jz7yverw9wq
SNS_PUBLISH_ARN: arn:aws:sns:eu-west-1:551709826462:TestPcsRaccoonResources-CommissionDataTopic-TRXW2GUZEVUC
TEST_MEDIA_BUCKET: testfbdtestinginfrastructure-testmediabucket-190bcnionyagx
S3_BATON: pcs-baton
#pdf
PDF_FOLDER_KEY: pdf
PDF_FILES: uid_version_AQC_PSE.pdf;uid_version_EYE.pdf;uid_version_PSE.pdf;uid_version_AQC.pdf
#pdf
#Baton folders
BATON_INCOMING: incoming
BATON_REPORTS: reports
TEST_DEV_BUCKET: testfbdtestinginfrastructure-testmediabucket-pjiaeml1v6wt
#Baton folders

#AWS
VERSION_NUMBER: '01'
CORE_NUMBER_TEMPLATE: ABTE(PLACEHOLDER_NUMBER)E
#TODO: this can be removed as a configuration going forward.
CORE_NUMBER: ABTE001E #sample
EPISODE_NAME: TEST_FBDS_EPISODE_NAME
UNDERSCORE_SEPARATOR: _
FORWARD_SLASH_SEPARATOR: /
#email related
FROM_EMAIL: testme@fbd.test.tools.bbc.co.uk
MEDIAFLEX_TEMPLATE: Mediaflex_template.csv
AMP_PAYLOAD_FILE_NAME: amp-payload_template
#email related

#dpp test files
VALID_DPP_FILES: TEST001Y_01.mxf
#File are categorised in With & Without checksum (; separated). Files in each category are separated using pipe(|) symbol.
INVALID_DPP_WITH_CHECKSUM_FILES: HEAD001N_01.mxf #;FALT001N_01.mxf
INVALID_DPP_WITHOUT_CHECKSUM_FILES: EMTY001N_01.mxf
#dpp test files

#splunk
SPLUNK_HOST: input-prd-p-3tfj2k7n9lm6.cloud.splunk.com
SPLUNK_USER_NAME: api_user
SPLUNK_PASSWORD: Splunk@P!URL
#splunk

#firefox_profile
FIREFOX_PROFILE: /Users/balona01/Library/Application Support/Firefox/profiles/vasws6rx.EndToEndTests
#firefox_profile


MXF_COPY_FILE_NAME: TEST001Y_01.mxf #this is a valid file for which checksum will be created.
MXF_COPY_FILE_RESOLUTION: HD
RETRIAL_PERIOD_IN_SECONDS: 30
CONFIGURABLE_TRIALS: 5

#for big files 
# MXF_COPY_FILE_NAME: TEST001Y_02.mxf
# #for big files put 120
# RETRIAL_PERIOD_IN_SECONDS: 120 
# CONFIGURABLE_TRIALS: 20
# #for big files 

WAIT_TIME_FOR_DATA_DISPLAY: 30

#database
ARRIVAL_TABLE: TestFbdReverbResources-FbdDynamoDBTable-8NMCBYRF9X2P
DEPARTURE_TABLE: TestFbdSharedResources-DeliveryStatusTable-ZG8GOSE2HEN6
#database

#UI
TEST_ENV_URL: https://fbd-dashboard.test.tools.bbc.co.uk
TOPICALITY: '10'
QC_STATE: PASS
AQC_STATE: PASS
SUPPLIER_TYPE: in-house #Supplier type values can be in-house, independent. Please note the "case" of the values.
SUPPLIER_NAME: TEST
WAIT_TIME_POST_UI_ACTION: 5
#UI

#TEST_ENV: int

# #AWS
# S3_ARRIVAL_BUCKET: testfbdmediasharedresources-filearrivalbucket-nasbfsnhm0my
# S3_VAULT_BUCKET:  	testfbdmediasharedresources-vaultbucket-1aaosuzno5noo
# S3_OUTBOUND_BUCKET: testfbdmediasharedresources-outboundmediabucket-10jz7yverw9wq
# SNS_PUBLISH_ARN: arn:aws:sns:eu-west-1:551709826462:TestPcsRaccoonResources-CommissionDataTopic-TRXW2GUZEVUC
# MXF_COPY_FILE_NAME: CYAC411B_02.mxf
# #AWS
# VERSION_NUMBER: '01.hd'
# CORE_NUMBER: onairid.ABTE001E
# EPISODE_NAME: TEST_FBDS_EPISODE_NAME
# SEPARATOR: 
# DATA_SEPARATOR: /
# #email related
# FROM_EMAIL: testme@fbd.test.tools.bbc.co.uk
# MEDIAFLEX_TEMPLATE: Mediaflex_template.csv
# AMP_PAYLOAD_FILE_NAME: amp-payload_template
# #email related

# #firefox_profile
# FIREFOX_PROFILE: /Users/balona01/Library/Application Support/Firefox/profiles/vasws6rx.EndToEndTests
# #firefox_profile

# #UI
# TEST_ENV_URL: https://fbd-dashboard.test.tools.bbc.co.uk/
# #UI
# RETRIAL_PERIOD_IN_SECONDS: 60
# WAIT_TIME_FOR_DATA_DISPLAY: 60

# #database
# ARRIVAL_TABLE: TestFbdReverbResources-FbdDynamoDBTable-8NMCBYRF9X2P
# DEPARTURE_TABLE: TestFbdSharedResources-DeliveryStatusTable-ZG8GOSE2HEN6
# #database

# #TEST_ENV: int